-- IMF World Economic Outlook Demo Setup
-- Generated by demo-builder skill
-- Re-runnable: uses CREATE OR REPLACE / IF NOT EXISTS

USE DATABASE API_DEMO;
USE SCHEMA PUBLIC;

-- ============================================================
-- INDICATOR_METADATA: human-readable names for IMF indicator codes
-- ============================================================
CREATE OR REPLACE TABLE INDICATOR_METADATA (
    INDICATOR       VARCHAR(50)     NOT NULL,
    INDICATOR_NAME  VARCHAR(200)    NOT NULL,
    UNIT            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(1000)   NOT NULL
);

INSERT INTO INDICATOR_METADATA VALUES
('BCA',          'Current Account Balance',                      'Billions USD',   'Current account balance in billions of U.S. dollars'),
('BCA_NGDPD',   'Current Account Balance (% of GDP)',            '% of GDP',       'Current account balance as a percentage of GDP'),
('GGXCNL_NGDP', 'Government Net Lending/Borrowing (% of GDP)',   '% of GDP',       'General government net lending/borrowing as a percentage of GDP'),
('GGXWDG_NGDP', 'Government Gross Debt (% of GDP)',              '% of GDP',       'General government gross debt as a percentage of GDP'),
('LP',           'Population',                                    'Millions',       'Total population in millions'),
('LUR',          'Unemployment Rate',                             '%',              'Unemployment rate as a percentage of total labor force'),
('NGDPD',        'GDP (Nominal)',                                 'Billions USD',   'Gross domestic product at current prices in billions of U.S. dollars'),
('NGDPDPC',      'GDP Per Capita (Nominal)',                      'USD',            'GDP per capita at current prices in U.S. dollars'),
('NGDP_RPCH',    'Real GDP Growth',                               '%',              'Annual percentage change in real GDP'),
('PCPIEPCH',     'Inflation (End of Period)',                      '%',              'End-of-period consumer price inflation'),
('PCPIPCH',      'Inflation (Average)',                            '%',              'Average consumer price inflation'),
('PPPEX',        'PPP Exchange Rate',                              'National/USD',   'Implied purchasing power parity exchange rate'),
('PPPGDP',       'GDP (PPP)',                                     'Billions Intl$', 'GDP based on purchasing power parity in billions of international dollars'),
('PPPPC',        'GDP Per Capita (PPP)',                           'Intl$',          'GDP per capita based on purchasing power parity in international dollars'),
('PPPSH',        'Share of World GDP (PPP)',                       '%',              'Share of world GDP based on purchasing power parity');

-- ============================================================
-- COUNTRY_METADATA: country names, regions, income groups
-- ============================================================
CREATE OR REPLACE TABLE COUNTRY_METADATA (
    COUNTRY_CODE    VARCHAR(10)     NOT NULL,
    COUNTRY_NAME    VARCHAR(200)    NOT NULL,
    REGION          VARCHAR(100)    NOT NULL,
    INCOME_GROUP    VARCHAR(50)     NOT NULL,
    IS_G7           BOOLEAN         DEFAULT FALSE,
    IS_G20          BOOLEAN         DEFAULT FALSE,
    IS_EMERGING     BOOLEAN         DEFAULT FALSE
);

INSERT INTO COUNTRY_METADATA VALUES
-- G7 + Major Advanced
('USA', 'United States',        'North America',        'High Income',          TRUE,  TRUE,  FALSE),
('GBR', 'United Kingdom',       'Europe',               'High Income',          TRUE,  TRUE,  FALSE),
('FRA', 'France',               'Europe',               'High Income',          TRUE,  TRUE,  FALSE),
('DEU', 'Germany',              'Europe',               'High Income',          TRUE,  TRUE,  FALSE),
('JPN', 'Japan',                'Asia Pacific',         'High Income',          TRUE,  TRUE,  FALSE),
('CAN', 'Canada',               'North America',        'High Income',          TRUE,  TRUE,  FALSE),
('ITA', 'Italy',                'Europe',               'High Income',          TRUE,  TRUE,  FALSE),
('AUS', 'Australia',            'Asia Pacific',         'High Income',          FALSE, TRUE,  FALSE),
('KOR', 'Korea',                'Asia Pacific',         'High Income',          FALSE, TRUE,  FALSE),
-- G20 Emerging
('CHN', 'China',                'Asia Pacific',         'Upper Middle Income',  FALSE, TRUE,  TRUE),
('IND', 'India',                'Asia Pacific',         'Lower Middle Income',  FALSE, TRUE,  TRUE),
('BRA', 'Brazil',               'Latin America',        'Upper Middle Income',  FALSE, TRUE,  TRUE),
('RUS', 'Russia',               'Europe & Central Asia','Upper Middle Income',  FALSE, TRUE,  TRUE),
('MEX', 'Mexico',               'Latin America',        'Upper Middle Income',  FALSE, TRUE,  TRUE),
('IDN', 'Indonesia',            'Asia Pacific',         'Upper Middle Income',  FALSE, TRUE,  TRUE),
('TUR', 'Turkey',               'Europe & Central Asia','Upper Middle Income',  FALSE, TRUE,  TRUE),
('SAU', 'Saudi Arabia',         'Middle East',          'High Income',          FALSE, TRUE,  TRUE),
('ZAF', 'South Africa',         'Sub-Saharan Africa',   'Upper Middle Income',  FALSE, TRUE,  TRUE),
('ARG', 'Argentina',            'Latin America',        'Upper Middle Income',  FALSE, TRUE,  TRUE),
-- Other notable economies
('ESP', 'Spain',                'Europe',               'High Income',          FALSE, FALSE, FALSE),
('NLD', 'Netherlands',          'Europe',               'High Income',          FALSE, FALSE, FALSE),
('CHE', 'Switzerland',          'Europe',               'High Income',          FALSE, FALSE, FALSE),
('SWE', 'Sweden',               'Europe',               'High Income',          FALSE, FALSE, FALSE),
('NOR', 'Norway',               'Europe',               'High Income',          FALSE, FALSE, FALSE),
('POL', 'Poland',               'Europe',               'Upper Middle Income',  FALSE, FALSE, TRUE),
('SGP', 'Singapore',            'Asia Pacific',         'High Income',          FALSE, FALSE, FALSE),
('THA', 'Thailand',             'Asia Pacific',         'Upper Middle Income',  FALSE, FALSE, TRUE),
('VNM', 'Vietnam',              'Asia Pacific',         'Lower Middle Income',  FALSE, FALSE, TRUE),
('MYS', 'Malaysia',             'Asia Pacific',         'Upper Middle Income',  FALSE, FALSE, TRUE),
('PHL', 'Philippines',          'Asia Pacific',         'Lower Middle Income',  FALSE, FALSE, TRUE),
('CHL', 'Chile',                'Latin America',        'High Income',          FALSE, FALSE, TRUE),
('COL', 'Colombia',             'Latin America',        'Upper Middle Income',  FALSE, FALSE, TRUE),
('PER', 'Peru',                 'Latin America',        'Upper Middle Income',  FALSE, FALSE, TRUE),
('EGY', 'Egypt',                'Middle East',          'Lower Middle Income',  FALSE, FALSE, TRUE),
('NGA', 'Nigeria',              'Sub-Saharan Africa',   'Lower Middle Income',  FALSE, FALSE, TRUE),
('KEN', 'Kenya',                'Sub-Saharan Africa',   'Lower Middle Income',  FALSE, FALSE, TRUE),
('ETH', 'Ethiopia',             'Sub-Saharan Africa',   'Low Income',           FALSE, FALSE, TRUE),
('BGD', 'Bangladesh',           'Asia Pacific',         'Lower Middle Income',  FALSE, FALSE, TRUE),
('PAK', 'Pakistan',             'Asia Pacific',         'Lower Middle Income',  FALSE, FALSE, TRUE),
('IRN', 'Iran',                 'Middle East',          'Lower Middle Income',  FALSE, FALSE, TRUE),
('IRQ', 'Iraq',                 'Middle East',          'Upper Middle Income',  FALSE, FALSE, TRUE),
('ARE', 'United Arab Emirates', 'Middle East',          'High Income',          FALSE, FALSE, FALSE),
('ISR', 'Israel',               'Middle East',          'High Income',          FALSE, FALSE, FALSE),
('NZL', 'New Zealand',          'Asia Pacific',         'High Income',          FALSE, FALSE, FALSE),
('IRL', 'Ireland',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('DNK', 'Denmark',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('FIN', 'Finland',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('AUT', 'Austria',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('BEL', 'Belgium',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('PRT', 'Portugal',             'Europe',               'High Income',          FALSE, FALSE, FALSE),
('GRC', 'Greece',               'Europe',               'High Income',          FALSE, FALSE, FALSE),
('CZE', 'Czech Republic',       'Europe',               'High Income',          FALSE, FALSE, FALSE),
('ROU', 'Romania',              'Europe',               'Upper Middle Income',  FALSE, FALSE, TRUE),
('HUN', 'Hungary',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('UKR', 'Ukraine',              'Europe & Central Asia','Lower Middle Income',  FALSE, FALSE, TRUE),
('ISL', 'Iceland',              'Europe',               'High Income',          FALSE, FALSE, FALSE),
('LUX', 'Luxembourg',           'Europe',               'High Income',          FALSE, FALSE, FALSE),
('PRY', 'Paraguay',             'Latin America',        'Upper Middle Income',  FALSE, FALSE, TRUE),
('URY', 'Uruguay',              'Latin America',        'High Income',          FALSE, FALSE, FALSE),
('ECU', 'Ecuador',              'Latin America',        'Upper Middle Income',  FALSE, FALSE, TRUE);

-- ============================================================
-- Verify setup
-- ============================================================
SELECT 'INDICATOR_METADATA' AS table_name, COUNT(*) AS row_count FROM INDICATOR_METADATA
UNION ALL
SELECT 'COUNTRY_METADATA', COUNT(*) FROM COUNTRY_METADATA
UNION ALL
SELECT 'IMF_DATAMAPPER_INDICATORS', COUNT(*) FROM IMF_DATAMAPPER_INDICATORS;
