-- Snowflake setup for the Openflow Financial Services Workshop.
-- Creates the NASDAQ_DEMO database, OPENFLOW_RUNTIME_ROLE, stage, and permissions required by the workshop.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS NASDAQ_DEMO;
USE DATABASE NASDAQ_DEMO;

-- Stage for unstructured earnings report PDFs
CREATE OR REPLACE STAGE EARNINGS_REPORTS_STAGE
    ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = ( ENABLE = TRUE );

-- Openflow runtime role
-- See: https://docs.snowflake.com/en/user-guide/data-integration/openflow/setup-openflow-spcs-create-rr
CREATE ROLE IF NOT EXISTS OPENFLOW_RUNTIME_ROLE;
GRANT ROLE OPENFLOW_RUNTIME_ROLE TO ROLE ACCOUNTADMIN;

-- Permissions for the Openflow runtime role
GRANT USAGE ON DATABASE NASDAQ_DEMO TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT CREATE SCHEMA ON DATABASE NASDAQ_DEMO TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT USAGE ON SCHEMA NASDAQ_DEMO.PUBLIC TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT CREATE TABLE ON SCHEMA NASDAQ_DEMO.PUBLIC TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT READ ON STAGE EARNINGS_REPORTS_STAGE TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT WRITE ON STAGE EARNINGS_REPORTS_STAGE TO ROLE OPENFLOW_RUNTIME_ROLE;

-- Allow ACCOUNTADMIN to read tables created by the Openflow runtime in any schema
GRANT SELECT ON FUTURE TABLES IN DATABASE NASDAQ_DEMO TO ROLE ACCOUNTADMIN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NASDAQ_DEMO TO ROLE ACCOUNTADMIN;
